import React, { useState, useEffect } from 'react';
import { Sparkles, CheckCircle2, Target, GraduationCap, Layers, Loader2, AlertCircle, RefreshCw } from 'lucide-react';
import { AIService, AIBookSummary } from '../services/api';
import { Book } from '../types';

interface AIBookSummaryCardProps {
  book: Book;
}

export const AIBookSummaryCard: React.FC<AIBookSummaryCardProps> = ({ book }) => {
  const [summary, setSummary] = useState<AIBookSummary | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  const fetchSummary = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await AIService.getBookSummary(book.id);
      setSummary(data);
    } catch (err: any) {
      setError(err.message || 'Could not generate summary.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSummary();
  }, [book.id]);

  if (loading) {
    return (
      <div className="bg-gradient-to-br from-indigo-50/50 via-purple-50/30 to-slate-50 dark:from-indigo-950/20 dark:via-purple-950/10 dark:to-slate-900 border border-indigo-100 dark:border-indigo-900/40 rounded-2xl p-6 sm:p-8 flex flex-col items-center justify-center min-h-[260px] text-center">
        <Loader2 className="w-8 h-8 text-indigo-600 dark:text-indigo-400 animate-spin mb-3" />
        <h4 className="font-semibold text-slate-800 dark:text-slate-200 text-sm">
          Synthesizing AI Academic Summary...
        </h4>
        <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 max-w-sm">
          Extracting key learning outcomes, prerequisites, and concepts from verified catalog metadata.
        </p>
      </div>
    );
  }

  if (error || !summary) {
    return (
      <div className="bg-slate-50 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 text-center">
        <AlertCircle className="w-6 h-6 text-amber-500 mx-auto mb-2" />
        <p className="text-xs text-slate-600 dark:text-slate-400 mb-3">
          {error || 'AI Summary could not be retrieved at this time.'}
        </p>
        <button
          onClick={fetchSummary}
          className="inline-flex items-center px-3 py-1.5 rounded-lg text-xs font-medium bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 transition-colors"
        >
          <RefreshCw className="w-3 h-3 mr-1.5" /> Try Again
        </button>
      </div>
    );
  }

  return (
    <div className="bg-gradient-to-br from-slate-50 via-indigo-50/20 to-purple-50/20 dark:from-slate-900 dark:via-indigo-950/10 dark:to-purple-950/10 border border-slate-200 dark:border-indigo-900/40 rounded-2xl p-6 sm:p-8 space-y-6 shadow-xs">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200/80 dark:border-slate-800 pb-4">
        <div className="flex items-center space-x-2.5">
          <div className="w-8 h-8 rounded-lg bg-indigo-600 text-white flex items-center justify-center shadow-xs">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="font-bold text-slate-900 dark:text-white text-base">
              AI Academic Summary & Synthesis
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Generated by Gemini 3.8 Flash • Grounded strictly on textbook metadata
            </p>
          </div>
        </div>

        <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-indigo-100 dark:bg-indigo-950/80 text-indigo-700 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800">
          <Sparkles className="w-3 h-3 mr-1 text-indigo-500" />
          {summary.aiPowered ? 'AI Verified' : 'Catalog Summary'}
        </span>
      </div>

      {/* Synthesis Paragraph */}
      <div>
        <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">
          Executive Overview
        </h4>
        <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
          {summary.shortSummary}
        </p>
      </div>

      {/* Grid of Key Insights */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Key Takeaways */}
        <div className="bg-white/80 dark:bg-slate-800/80 rounded-xl p-4 border border-slate-200/80 dark:border-slate-700/60 shadow-xs">
          <div className="flex items-center space-x-2 text-indigo-600 dark:text-indigo-400 mb-3">
            <CheckCircle2 className="w-4 h-4" />
            <h5 className="font-semibold text-xs uppercase tracking-wider text-slate-900 dark:text-white">
              Key Learning Outcomes
            </h5>
          </div>
          <ul className="space-y-2">
            {summary.keyTakeaways.map((takeaway, idx) => (
              <li key={idx} className="flex items-start text-xs text-slate-600 dark:text-slate-300">
                <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 mr-2 shrink-0" />
                <span>{takeaway}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Topics & Prerequisites */}
        <div className="bg-white/80 dark:bg-slate-800/80 rounded-xl p-4 border border-slate-200/80 dark:border-slate-700/60 shadow-xs space-y-4">
          <div>
            <div className="flex items-center space-x-2 text-purple-600 dark:text-purple-400 mb-2">
              <Layers className="w-4 h-4" />
              <h5 className="font-semibold text-xs uppercase tracking-wider text-slate-900 dark:text-white">
                Core Covered Topics
              </h5>
            </div>
            <div className="flex flex-wrap gap-1.5">
              {summary.keyTopics.map((topic, idx) => (
                <span
                  key={idx}
                  className="px-2 py-0.5 rounded-md text-[11px] font-medium bg-slate-100 dark:bg-slate-700 text-slate-700 dark:text-slate-200 border border-slate-200 dark:border-slate-600"
                >
                  {topic}
                </span>
              ))}
            </div>
          </div>

          <div className="border-t border-slate-100 dark:border-slate-700/60 pt-3">
            <div className="flex items-center space-x-2 text-emerald-600 dark:text-emerald-400 mb-1.5">
              <Target className="w-4 h-4" />
              <h5 className="font-semibold text-xs uppercase tracking-wider text-slate-900 dark:text-white">
                Target Audience
              </h5>
            </div>
            <p className="text-xs text-slate-600 dark:text-slate-300">
              {summary.targetAudience}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
